CREATE DATABASE IF NOT EXISTS Test;
USE Test;

CREATE TABLE IF NOT EXISTS SensorData (
    id INT AUTO_INCREMENT PRIMARY KEY,
    sensor VARCHAR(50),
    location VARCHAR(50),
    value1 FLOAT,
    value2 FLOAT,
    value3 FLOAT,
    reading_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS LightControl (
    id INT AUTO_INCREMENT PRIMARY KEY,
    state ENUM('ON', 'OFF') DEFAULT 'OFF',
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
); 